### ISSUE TITLE
Do not display category tags which appear in detail text

### ISSUE THREAD

**Issue by supasate** [youpin-city/youpin-web#9]
Related to youpin-city/youpin-bot#9.

As we discussed about this issue, in this case, a user writes detail text that contains a hash tag which is the same as the category tag.

The API is alright to separately send the detail text and tags out, but, a tag which is already in the detail text should be removed in the display logic.

**Comment by rapee** [comment]
Sorry for my late response.

I think the duplicated tags should not be removed in display logic.
The reason is that tags are part of a text that user describes something legible.
Ex. we have a category ["footpath"] and text:

```
look at this #dirty #footpath over there!
```

With above logic, the text would become

```
look at this #dirty over there!
```

which does not make sense.

I think text (and tags) display should be the same, but we omit duplicated categories instead.

**Comment by supasate** [comment]
My issue title is ambiguous. I mean **Do not display _category_ tags which appear in detail text**.

So, if we have a category ["footpath"] and text: 

```
look at this #dirty #footpath over there!
```

it should display just 

```
look at this #dirty #footpath over there!
```

not 

```
look at this #dirty #footpath over there! #footpath
```

**Comment by p16i** [comment]
ic, now it makes more sense 😄

**Comment by rapee** [comment]
Done
